---
- hosts: all
  become: yes

  tasks:

    - name: install java
      yum:

        name: java-1.8.0-openjdk
        state: present

    - name: download tomcat
      get_url:

        url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.64/bin/apache-tomcat-9.0.64.tar.gz
        dest: /root

    - name: extract tomcat
      unarchive:

         src: apache-tomcat-9.0.64.tar.gz
         dest: /root
         remote_src: true

    - name: copy artifact
      copy:

         src: /home/ec2-user
         dest: /root/apache-tomcat-9.0.64/webapps
